feat: criação de tabelas por função
ronaldosc/desafio-analise-dados-procons pull request #29
Opened 2023-07-04 22:35 UTC by ronaldosc

Agora temos uma função que cria as tabelas, com tratamento de erros.
Ela se baseia no próprio arquivo .sql criado.

2023-07-04 22:38 UTC, ronaldosc commented
Uma oportunidade que identifquei e para simplificar a conexão com o banco de dados apenas com um URI (link único) é usar o `psycopg`, veja que é diferente do que estamos usando o `psycopg2` , e nessa com apenas o nome pegará a versão mais atual que é >3 .

2023-07-04 23:13 UTC, viniam requested changes
Recebi esse erro, talvez é a forma que foi importado, chegou a testar?


```
  File "procons\src\database\database_config.py", line 17, in create_connection
    conn = pg.connect(
           ^^^^^^^^^^
AttributeError: module 'psycopg2._psycopg' has no attribute 'connect'. Did you mean: '_connect'?
```

2023-07-05 00:12 UTC, viniam requested changes
```
Database connected successfully
Erro ao criar tabelas.
    Mensagem de erro: <class 'psycopg2.Error'>
```

Também não funciona direto da pasta raiz, tem que entrar na src/database

2023-07-05 01:18 UTC, viniam approved these changes
Funcionando

2023-07-05 01:50 UTC, merged